### ISSUE TITLE
mantle.LUT documentation is misleading

### ISSUE THREAD

**Issue by akeley98** [phanrahan/mantle#75]
The documentation claims that an N-bit LUT has an N-bit 'bits' input I and a 'bit' output O. However, the input is actually separated out into individual bit inputs I0, I1, ... I{N}.
```
>>> import mantle
>>> mantle.LUT([0,1]*8, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/Documents/aha/magmathon/mantle/mantle/coreir/LUT.py", line 61, in LUT
    return DefineLUT(init, N)()
  File "/home/david/Documents/aha/magmathon/mantle/mantle/coreir/LUT.py", line 28, in DefineLUT
    class LUT(Circuit):
  File "/home/david/Documents/aha/magmathon/magma/magma/circuit.py", line 421, in __new__
    self.definition()
  File "/home/david/Documents/aha/magmathon/mantle/mantle/coreir/LUT.py", line 33, in definition
    lutN = DeclareCoreirLUT(N, init)()
  File "/home/david/Documents/aha/magmathon/magma/magma/circuit.py", line 532, in wrapped
    result = func(*args, **kwargs)
  File "/home/david/Documents/aha/magmathon/mantle/mantle/coreir/LUT.py", line 19, in DeclareCoreirLUT
    coreir_configargs = {"init": coreir.BitVector(1<<N, init)})
AttributeError: module 'coreir' has no attribute 'BitVector'
>>> lut = mantle.LUT([0,1]*8, 4)
>>> print(mantle.LUT.__doc__)

    n-bit LUT

    I : In(Bits(n)), O : Out(Bit)
    
>>> print(lut.IO)
"I0", In(Bit), "I1", In(Bit), "I2", In(Bit), "I3", In(Bit), "O", Out(Bit)
```

**Comment by phanrahan** [comment]
Fixed.
